- name: Install dependencies for frontend
  hosts: all
  become: yes
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Add NodeSource repository
      shell: curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install npm dependencies
      npm:
        path: Frontend
        state: present
