name: Test, Build, Deploy (Groep 5)

on:
  push:
    branches:
      - 'groep_5_b2d'
      - 'groep_5_b2d_test'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build program
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Slack Notification after Test
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbqj9Ii13d6hx5a9kyLnC5A8A96LDSaSZv_w&s
          SLACK_USERNAME: Github (Frontend)
          SLACK_WEBHOOK: ${{ secrets.GROEP_5_SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Tests completed with status: ${{ job.status }}"

  start-vm:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Start Azure VM
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_GROEP5_CREDENTIALS }}
      - run: |
          az vm start --name Groep5.2 --resource-group B2C6D --no-wait

  deploy:
    needs: start-vm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_GROEP5_CREDENTIALS }}

      - name: Deploy to Azure VM
        env:
          AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
          AZURE_VM_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
          AZURE_VM_PASSWORD: ${{ secrets.AZURE_VM_PASSWORD }}
          APPLICATION_PATH: /home/$AZURE_VM_USERNAME/nextjs
        run: |
          sshpass -p azurepass ssh -tt azureuser@51.144.74.229 << 'EOF'
            set -e
            cd /home/azureuser/nextjs
            git init
            git remote add origin https://github.com/ZuydUniversity/B2C6_B2D_Frontend
            git pull origin groep_5_b2d_test
            npm install
            npm run build
            pm2 restart all || pm2 start npm --name "nextjs-app" -- start
          EOF

      - name: Share IP Address
        run: echo "Application deployed to http://${{ secrets.AZURE_VM_GROEP5_IP }}" > deployment_info.txt
        id: deployment_info

      - name: Slack Notification with IP
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: good
          SLACK_ICON: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbqj9Ii13d6hx5a9kyLnC5A8A96LDSaSZv_w&s
          SLACK_USERNAME: Github (Frontend)
          SLACK_WEBHOOK: ${{ secrets.GROEP_5_SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Deployment successful! Your application is available at http://${{ secrets.AZURE_VM_GROEP5_IP }}"

  slackNotification:
    needs: [test, deploy]
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbqj9Ii13d6hx5a9kyLnC5A8A96LDSaSZv_w&s
          SLACK_USERNAME: Github (Frontend)
          SLACK_WEBHOOK: ${{ secrets.GROEP_5_SLACK_WEBHOOK }}
