name: Build and Deploy NEXT.js App

on:
  push:
    branches:
      - "groep_1_B2D_Said_Amghar"

env:
  HOST: 52.166.135.125
  SERVER_USER: groep1
  SERVER_PASSWORD: Welkomwelkom123!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build
      
      - name: Build FrontEnd artifacts
        run: | 
          mkdir FrontEnd
          cp -r .next public package.json FrontEnd/
      - 
        name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FrontEnd
          path: FrontEnd

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: FrontEnd
          path: FrontEnd

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # - name: Install dependencies
      #   run: npm install

      - name: Install sshpass & rsync
        run: |
          sudo apt-get install -y sshpass
          sudo apt-get install rsync

      # - name: Configure SSH
      #   run: |
      #     mkdir -p $HOME/.ssh
      #     echo -e "Host 52.166.135.125\n\tStrictHostKeyChecking no" > $HOME/.ssh/config

      - name: Deploy to Server
        run: |
          sudo apt-get install rsync
          sshpass -p ${{env.SERVER_PASSWORD}} ssh -o StrictHostKeyChecking=no ${{env.SERVER_USER}}@${{env.HOST}} "sudo mkdir -p FrontEnd"
          ls
          sshpass -p ${{env.SERVER_PASSWORD}} rsync -rvz -e 'ssh -o StrictHostKeyChecking=no' --progress FrontEnd/ ${{env.SERVER_USER}}@${{env.HOST}}:/FrontEnd
          
          
      # - name: SSH into Server and run npm install
      #   env:
      #     SERVER_PASSWORD: Welkomwelkom123!
      #   run: |
      #     sshpass -p $SERVER_PASSWORD ssh groep1@52.166.135.125 "cd /FrontEnd/ && npm install"
  
      # - name: Restart Application
      #   run: |
      #     ssh groep1@52.166.135.125 "cd FrontEnd && npm run start -- -p 80"
