name: Build and Deploy NEXT.js App
on:
  push:
    branches:
      - "geen"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: .next
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: nextjs-build
          path: .next

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Server
        run: |
          rsync -avz --delete .next/ groep1@52.166.135.125:/path/to/your/app/.next
          rsync -avz --delete public/ groep1@52.166.135.125:/path/to/your/app/public
          rsync -avz --delete package.json groep1@52.166.135.125:/path/to/your/app/package.json
          ssh groep1@52.166.135.125 "cd /path/to/your/app && npm install"

      - name: Restart Application
        run: |
          ssh groep1@52.166.135.125 "pm2 restart my-nextjs-app || pm2 start npm --name 'my-nextjs-app' -- run start"