name: Build and Deploy NEXT.js App

on:
  push:
    branches:
      - "groep_1_B2D_Said_Amghar"

env:
  HOST: 52.166.135.125
  SERVER_USER: groep1
  SERVER_PASSWORD: Welkomwelkom123!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build
      
      - name: Build FrontEnd artifacts
        run: | 
          mkdir FrontEnd
          cp -r .next public package.json FrontEnd/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FrontEnd
          path: FrontEnd

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: FrontEnd
          path: FrontEnd
      
      - name: Clean Old Artefact
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{env.HOST}}
          username: ${{env.SERVER_USER}}
          password: ${{env.SERVER_PASSWORD}}
          script: |
            sudo rm -r FrontEnd
            
      - name: Deploy to Server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: FrontEnd
          remote: FrontEnd
          host: ${{env.HOST}}
          username: ${{env.SERVER_USER}}
          password: ${{env.SERVER_PASSWORD}}

      - name: Install Node.js and dependenties
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{env.HOST}}
          username: ${{env.SERVER_USER}}
          password: ${{env.SERVER_PASSWORD}}
          script: |
            sudo apt update
            sudo apt install curl -y
            curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash - 
            sudo apt-get install -y nodejs
            cd FrontEnd
            sudo npm install
  
      - name: Restart Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{env.HOST}}
          username: ${{env.SERVER_USER}}
          password: ${{env.SERVER_PASSWORD}}
          script: |
            cd FrontEnd
            nohup sudo npm run start -- -p 80 >frontend.log 2>&1 </dev/null & 
          
