name: Build and Deploy NEXT.js App

on:
  push:
    branches:
      - "groep_1_B2D_Said_Amghar"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: .next

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: .next

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Copy build artifacts to server
        env:
          SERVER_PASSWORD: Welkomwelkom123!
        run: |
          scp -r .next/ groep1@52.166.135.125:~/.next
          scp -r public/ groep1@52.166.135.125:~/public
          scp package.json groep1@52.166.135.125:~/package.json

      - name: SSH into Server and move files to FrontEnd directory
        env:
          SERVER_PASSWORD: Welkomwelkom123!
        run: |
          sshpass -p $SERVER_PASSWORD ssh groep1@52.166.135.125 "mv ~/.next /FrontEnd/.next && mv ~/public /FrontEnd/public && mv ~/package.json /FrontEnd/package.json"
          
      - name: SSH into Server and run npm install
        env:
          SERVER_PASSWORD: Welkomwelkom123!
        run: |
          sshpass -p $SERVER_PASSWORD ssh groep1@52.166.135.125 "cd /FrontEnd/ && npm install"
  
      - name: Restart Application
        run: |
          ssh groep1@52.166.135.125 "cd FrontEnd && npm run start -- -p 80"
