name: Build and Deploy NEXT.js App

on:
  push:
    branches:
      - "groep_1_B2D_Said_Amghar"

env:
  HOST: 52.166.135.125
  SERVER_USER: groep1
  SERVER_PASSWORD: Welkomwelkom123!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build
      
      - name: Build FrontEnd artifacts
        run: | 
          mkdir FrontEnd
          cp -r .next public package.json FrontEnd/
      - 
        name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FrontEnd
          path: FrontEnd

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: FrontEnd
          path: FrontEnd
      
      - name: Install Node.js on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{env.HOST}}
          username: ${{env.SERVER_USER}}
          password: ${{env.SERVER_PASSWORD}}
          script: |
            npm -v &&  npm install npm@latest -g && npm -v
            sudo npm cache clean -f && sudo npm install -g n && sudo n stable
          

      - name: Deploy to Server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: FrontEnd
          remote: FrontEnd
          host: ${{env.HOST}}
          username: ${{env.SERVER_USER}}
          password: ${{env.SERVER_PASSWORD}}
          
      - name: SSH into Server and run npm install
        run: |
          sshpass -p ${{env.SERVER_PASSWORD}} ssh ${{env.SERVER_USER}}@${{env.HOST}} "cd FrontEnd && npm install" 
  
      # - name: Restart Application
      #   run: |
      #     ssh groep1@52.166.135.125 "cd FrontEnd && npm run start -- -p 80"
