name: main

on:
  push:
  workflow_dispatch:

jobs:
  #testing:
  #  uses: ZuydUniversity/B2C6_B2D_Frontend/.github/workflows/testing.yml@groep-2

  build:
    # needs: testing
    uses: ZuydUniversity/B2C6_B2D_Frontend/.github/workflows/build.yml@groep-2

  deploy:
    needs: build
    uses: ZuydUniversity/B2C6_B2D_Frontend/.github/workflows/deploy.yml@groep-2
