name: main

on:
  push:

jobs:
  #testing:
  #  uses: ZuydUniversity/B2C6_B2D_Frontend/.github/workflows/testing.yml@groep-2

  build:
    # needs: testing
    uses: ZuydUniversity/B2C6_B2D_Frontend/.github/workflows/build.yml@groep-2
    secrets:
      GROEP_2_DOCKERHUB_USERNAME: ${{ secrets.GROEP_2_DOCKERHUB_USERNAME }}
      GROEP_2_DOCKERHUB_TOKEN: ${{ secrets.GROEP_2_DOCKERHUB_TOKEN }}
      GROEP_2_DOCKERHUB_FRONTEND_REPO_NAME: ${{secrets.GROEP_2_DOCKERHUB_FRONTEND_REPO_NAME}}
    with:
      version: ${{version}}

  deploy:
    needs: build
    uses: ZuydUniversity/B2C6_B2D_IAS/.github/workflows/run_docker_via_ssh.yml@groep-2
