name: main         

on:
  push:

jobs:
  build:
    uses: ZuydUniversity/B2C6_B2D_IAS/.github/workflows/build.yml@groep-2
    secrets: inherit

  deploy:
    needs: build
    uses: ZuydUniversity/B2C6_B2D_IAS/.github/workflows/deploy.yml@groep-2
    secrets: inherit
