name: Security Tests

on:
  push:
    branches:
      - 'groep_5_b2d'
      - 'groep_5_b2d_test'

jobs:
  security-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run npm audit
      run: npm audit --audit-level=high

    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/setup@v1
      with:
        version: '1.840.0'
    - name: Authenticate Snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk auth $SNYK_TOKEN
    - name: Snyk Test
      run: snyk test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t myapp:latest .

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'myapp:latest'

  slackNotification:
    needs: security-tests
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbqj9Ii13d6hx5a9kyLnC5A8A96LDSaSZv_w&s
          SLACK_USERNAME: Github (Frontend)
          SLACK_WEBHOOK: ${{ secrets.GROEP_5_SLACK_WEBHOOK }}