name: Test and Build (Groep 5)

on:
  push:
    branches:
      - 'groep_5_b2d'
      - 'groep_5_b2d_test'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build program
        run: npm run build

      - name: Run tests
        run: npm test
