name: Test and Build (Groep 5).

on:
  push:
    branches:
      - 'groep_5_b2d'
      - 'groep_5_b2d_test'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build program
        run: npm run build

      - name: Run tests
        run: npm test

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbqj9Ii13d6hx5a9kyLnC5A8A96LDSaSZv_w&s
        SLACK_USERNAME: Github (Frontend)
        SLACK_WEBHOOK: ${{ secrets.GROEP_5_SLACK_WEBHOOK }}
